name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v6

    - uses: actions/checkout@v3
      with:
        image_name: anilguvenc/flutter-web-builder 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag satta-seller-web
