name: Gh-Pages

on:
  push:
    branches: [ gh-pages ]

jobs:
  generate_web:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action